"""Recreate lunch table with id

Revision ID: 3b05ded63fce
Revises: 4b73ccc35ec0
Create Date: 2025-10-21 19:48:37.741684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b05ded63fce'
down_revision = '4b73ccc35ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('allergens',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ordered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch', schema=None) as batch_op:
        batch_op.alter_column('ordered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allergens',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
