"""Add Lunch table

Revision ID: 9d940a490155
Revises: 3b05ded63fce
Create Date: 2025-10-21 20:00:11.686361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d940a490155'
down_revision = '3b05ded63fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch', schema=None) as batch_op:
        batch_op.alter_column('allergens',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ordered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch', schema=None) as batch_op:
        batch_op.alter_column('ordered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allergens',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
