"""Initial migration.

Revision ID: 4b73ccc35ec0
Revises: 6756d5ea0976
Create Date: 2025-10-21 19:27:27.077990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b73ccc35ec0'
down_revision = '6756d5ea0976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunch',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('allergens', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ordered', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
