"""Initial migration.

Revision ID: 6756d5ea0976
Revises: 
Create Date: 2025-10-19 15:30:43.738022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6756d5ea0976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unknown')
    op.drop_table('7_G')
    op.drop_table('lunch')
    op.drop_table('3_P')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('3_P',
    sa.Column('rid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teacher', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('room', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rid', name=op.f('3_P_pkey'))
    )
    op.create_table('lunch',
    sa.Column('Lid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('allergens', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ordered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Lid', name=op.f('lunch_pkey'))
    )
    op.create_table('7_G',
    sa.Column('rid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teacher', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('room', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rid', name=op.f('7_G_pkey'))
    )
    op.create_table('unknown',
    sa.Column('rid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teacher', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('room', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rid', name=op.f('unknown_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
